mongodb:
  connection:
    uri: mongodb://root:pwd@localhost:27017/admin
    database: admin
productInfo:
  baseUrl: http://localhost:8082/productInfoService/product/names
orderSearch:
  baseUrl: http://localhost:8081/orderSearchService/order/phone